SELECT 
    T1.REST_ID, 
    T1.REST_NAME, 
    T1.FOOD_TYPE, 
    T1.FAVORITES, 
    T1.ADDRESS, 
    ROUND(avg(T2.REVIEW_SCORE), 2) AS SCORE 
FROM (
    SELECT * 
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
) AS T1
INNER JOIN REST_REVIEW AS T2
ON T1.REST_ID = T2.REST_ID
GROUP BY T1.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;